description:
  "a sauce made of clarified butter emulsified in egg yolks and white wine vinegar and flavored with herbs"
type:
  "sauce"
ingredients:
  - butter, melted
  - chervil
  - egg yolk
  - shallots
  - tarragon
  - white wine vinegar