description:
  "an emulsion or suspension of small globules of oil and oil-soluble compounds in water and water-soluble compounds. Cooks may use egg or egg yolk as an emulsifier."
type:
  "condiment"
ingredients:
  - garlic
  - oil
  - egg yolk