description:
  "a variation of béarnaise without tarragon or chervil, plus tomato purée"
type:
  "sauce"
ingredients:
  - butter, melted
  - egg yolk
  - shallots
  - tomato pureée
  - white wine vinegar