description:
  "a creamy, pale yellow condiment based on an emulsion of about 25–50 percent oil in water, emulsified by egg yolk and acidulated by spirit vinegar"
type:
  "condiment"
ingredients:
  - egg yolk
  - oil
  - water
  - vinegar
